import axios from "axios";
import { createContext, useEffect, useState } from "react";

const MyContext = createContext();

const _LANGUAGE_ = {
    english: {
        serviceButton: "BACK TO SERVICES",
        getInTouch: "Call us",
        mailUs: "Email us",
        navbarItem1: "HOME",
        navbarItem2: "SERVICES",
        navbarItem3: "ABOUT",
        navbarItem4: "CONTACT",
        navbarLanguage: "LANGUAGE",
        onePage: "ONE-PAGE SITE",
        multiPage: "MULTI-PAGE SITE",
        ecommerce: "E-COMMERCE",
        mobileApps: "APPS",
        introSubHeader1: "Custom websites tailored to your business.",
        introSubHeader2: "Quality and hand-coded solutions.",
        introSubHeader3: "Your digital dreams, realized.",
        philosophyHeader: "OUR PHILOSOPHY",
        philosophyText1: "Clean code, design, and communication.",
        philosophyText2: "From idea to launch, we deliver impact.",
        philosophyClosing: "< Let's create your online experience />",
        whyUsHeader1: "Custom Development",
        whyUsText1:
            "Unique code for your business. Stunning, fast, and user-friendly designs on all devices.",
        whyUsHeader2: "Manual Coding",
        whyUsText2: "Hand-crafted sites: fast, secure, scalable, and reliable.",
        whyUsHeader3: "Future-Ready Apps",
        whyUsText3:
            "iOS & Android apps with React Native. Reach your audience everywhere.",
        whyUsHeader4: "Multilingual Service",
        whyUsText4:
            "We communicate in Dutch, French, and English, ensuring clarity for every client.",
        allServicesHeader: "How we help",
        allServicesSubHeader: "Services tailored to your needs",
        allServicesText:
            "We deliver personalized websites and apps to help your business stand out. From simple sites to complex platforms, we bring your ideas to life.",
        vitrineHeader: "Simple, impactful websites.",
        vitrineIntro1: "Affordable design: front and contact pages.",
        vitrineIntro2: "Introduce your business, services, and more.",
        vitrineIntro3: "Easy contact options: forms, links, and more.",
        vitrineIntro4: "Endless possibilities.",
        vitrinePerfect: "Ideal for",
        vitrineBenefitsHeader: "Benefits",
        vitrineBox1:
            "A single page with all key info, designed to grab attention and drive action.",
        vitrinePerfectFor: [
            "Event promotions",
            "Highlighting a product/service",
            "Simple portfolios",
            "Starting online",
        ],
        vitrineBenefits: [
            "Business domain name",
            "Quick setup, low cost",
            "Perfect for small businesses",
            "Mobile-friendly design",
        ],
        websiteHeader: "Websites that grow with you.",
        websiteIntro1: "Ideal for detailed, organized business info.",
        websiteIntro2: "From services to resources, showcase your work.",
        websiteIntro3: "Easy to navigate and explore.",
        websitePerfect: "Ideal for",
        websiteBenefitsHeader: "Benefits",
        websiteBox1:
            "Organized, multi-page layouts for seamless navigation and growth.",
        websitePerfectFor: [
            "Service companies",
            "Resource-sharing organizations",
            "Businesses with portfolios",
            "Content-driven platforms",
        ],
        websiteBenefits: [
            "Quick, easy info access",
            "Professional brand image",
            "Rich content options",
            "Scalable design for growth",
        ],
        ecommerceHeader: "Boost sales with seamless online shopping.",
        ecommerceIntro1: "Easy, effective e-commerce sites.",
        ecommerceIntro2: "From local shops to global brands.",
        ecommerceIntro3: "Secure, user-friendly stores for smooth management.",
        ecommerceIntro4: "Unlimited possibilities.",
        ecommercePerfect: "Ideal for",
        ecommerceBenefitsHeader: "Benefits",
        ecommerceBox1:
            "Custom or Shopify-based stores, optimized for sales and user experience.",
        ecommercePerfectFor: [
            "First-time online sellers",
            "Retailers expanding reach",
            "Tailored e-commerce solutions",
            "Secure payment options",
        ],
        ecommerceBenefits: [
            "Local and global sales",
            "Revenue 24/7",
            "Secure payments",
            "Branded, attractive designs",
        ],
        appDevHeader: "Mobile presence for your brand.",
        appDevIntro1: "Apps that make an impact.",
        appDevIntro2: "From food orders to unique solutions.",
        appDevIntro3: "Fast, reliable, and user-friendly apps.",
        appDevIntro4: "Support business growth on iOS and Android.",
        appDevPerfect: "Ideal for",
        appDevBenefitsHeader: "Benefits",
        appDevBox1:
            "Custom React Native apps: efficient, scalable, and seamless on iOS & Android.",
        appDevPerfectFor: [
            "Connecting with customers",
            "Streamlining processes",
            "Unique app ideas",
            "Scalable startups",
        ],
        appDevBenefits: [
            "Stay connected anytime",
            "Automated key functions",
            "One app for all devices",
            "User-friendly experience",
        ],
        aboutUsHeader: "Het team:",
        aboutLisa:
            "Lisa is the driving force behind Bel'Azur Coding. Without her, this site probably wouldn’t exist. Lisa has an eye for design, loves solving tough challenges, and doesn’t shy away from tackling difficulties. Thanks to her training at SheCodes, she is perfectly capable of building beautiful, mobile-friendly, and interactive websites that showcase your business in a new light.",
        aboutJoachim:
            "Joachim is the geek of the duo. He has always had a strong interest in web design and continuously acquires new skills. With a Full Stack certificate from 4Geeks Academy and a recent course on React Native, he is capable of developing complex and modern websites, e-commerce platforms, and mobile applications.",
        contactHeader: "Get in touch",
        contactFirstName: "First Name",
        contactLastName: "Last Name",
        contactPhone: "Phone",
        contactEmail: "Email",
        contactCompany: "Company",
        contactInterest: "I'm interested in",
        contactInterestOption1: "Select",
        contactInterestOption2: "One-Page Website",
        contactInterestOption3: "Multi-Page Website",
        contactInterestOption4: "E-commerce",
        contactInterestOption5: "Other",
        contactAdditionalInfo: "Additional info",
        contactButton: "Submit",
        contactIsRequired: "is required",
        contactNumeric: "Phone must be numeric",
        contactEmailError: "Invalid email",
        contactEmailRequired: "Email required",
        contactEmailSentSuccess: "Email sent!",
        contactEmailSentError: "Email failed. Try again.",
    },
    french: {
        serviceButton: "RETOUR AUX SERVICES",
        getInTouch: "Appelez-nous",
        mailUs: "Écrivez-nous",
        navbarItem1: "ACCUEIL",
        navbarItem2: "SERVICES",
        navbarItem3: "À PROPOS",
        navbarItem4: "CONTACT",
        navbarLanguage: "LANGUE",
        onePage: "SITE ONE-PAGE",
        multiPage: "SITE MULTI-PAGE",
        ecommerce: "E-COMMERCE",
        mobileApps: "APPLIS",
        introSubHeader1: "Sites personnalisés adaptés à votre activité.",
        introSubHeader2: "Qualité et solutions sur mesure.",
        introSubHeader3: "Vos rêves numériques, réalisés.",
        philosophyHeader: "PHILOSOPHIE",
        philosophyText1: "Code propre, design soigné, communication claire.",
        philosophyText2: "De l'idée au lancement, nous créons de l'impact.",
        philosophyClosing: "< Créons votre expérience en ligne />",
        whyUsHeader1: "Développement personnalisé",
        whyUsText1:
            "Code unique pour votre activité. Designs époustouflants, rapides et conviviaux.",
        whyUsHeader2: "Code manuel",
        whyUsText2:
            "Sites faits main : rapides, sécurisés, évolutifs et fiables.",
        whyUsHeader3: "Applications prêtes pour l’avenir",
        whyUsText3:
            "Applis iOS & Android avec React Native. Touchez votre audience partout.",
        whyUsHeader4: "Service multilingue",
        whyUsText4:
            "Nous communiquons en français, anglais et néerlandais pour une clarté optimale.",
        allServicesHeader: "Comment nous aidons",
        allServicesSubHeader: "Des services adaptés à vos besoins",
        allServicesText:
            "Sites et applis personnalisés pour mettre en valeur votre entreprise.",
        vitrineHeader: "Sites simples et impactants.",
        vitrineIntro1: "Design abordable : page d'accueil et contact.",
        vitrineIntro2: "Présentez votre activité, vos services, etc.",
        vitrineIntro3: "Options de contact faciles : formulaires, liens, etc.",
        vitrineIntro4: "Possibilités infinies.",
        vitrinePerfect: "Parfait pour",
        vitrineBenefitsHeader: "Avantages",
        vitrineBox1: "Une page unique avec toutes les infos clés.",
        vitrinePerfectFor: [
            "Promotions d’événements",
            "Mise en avant d'un produit/service",
            "Portfolios simples",
            "Démarrer en ligne",
        ],
        vitrineBenefits: [
            "Nom de domaine d’entreprise",
            "Mise en ligne rapide et économique",
            "Idéal pour les petites entreprises",
            "Design adapté au mobile",
        ],
        websiteHeader: "Sites qui évoluent avec vous.",
        websiteIntro1: "Idéal pour des infos détaillées et organisées.",
        websiteIntro2: "Présentez vos services et ressources.",
        websiteIntro3: "Navigation simple et intuitive.",
        websitePerfect: "Parfait pour",
        websiteBenefitsHeader: "Avantages",
        websiteBox1: "Des designs multi-pages pour une navigation fluide.",
        websitePerfectFor: [
            "Entreprises de services",
            "Partage de ressources",
            "Portfolios professionnels",
            "Plateformes de contenu",
        ],
        websiteBenefits: [
            "Accès rapide aux infos",
            "Image professionnelle",
            "Contenus variés",
            "Design évolutif",
        ],
        ecommerceHeader: "Boostez vos ventes en ligne.",
        ecommerceIntro1: "Sites e-commerce simples et efficaces.",
        ecommerceIntro2: "Pour les boutiques locales et marques globales.",
        ecommerceIntro3: "Boutiques sécurisées et conviviales.",
        ecommerceIntro4: "Possibilités infinies.",
        ecommercePerfect: "Parfait pour",
        ecommerceBenefitsHeader: "Avantages",
        ecommerceBox1: "Boutiques sur mesure ou basées sur Shopify.",
        ecommercePerfectFor: [
            "Premiers pas en ligne",
            "Commerces élargissant leur portée",
            "Solutions e-commerce personnalisées",
            "Paiements sécurisés",
        ],
        ecommerceBenefits: [
            "Ventes locales et internationales",
            "Revenus 24/7",
            "Paiements sécurisés",
            "Designs attractifs",
        ],
        appDevHeader: "Présence mobile pour votre marque.",
        appDevIntro1: "Applis à fort impact.",
        appDevIntro2: "Pour commandes ou solutions uniques.",
        appDevIntro3: "Applis rapides et fiables.",
        appDevIntro4: "Soutenez votre croissance sur iOS et Android.",
        appDevPerfect: "Parfait pour",
        appDevBenefitsHeader: "Avantages",
        appDevBox1:
            "Applis React Native sur mesure : performantes et évolutives.",
        appDevPerfectFor: [
            "Connexion avec les clients",
            "Optimisation des processus",
            "Idées d’applis uniques",
            "Startups évolutives",
        ],
        appDevBenefits: [
            "Connexion à tout moment",
            "Automatisation des fonctions clés",
            "Une seule appli pour tous les appareils",
            "Expérience utilisateur optimisée",
        ],
        aboutUsHeader: "L'equipe:",
        aboutLisa:
            "Lisa est la force motrice de Bel'Azur Coding. Sans elle, ce site n'existerait probablement pas. Lisa a un œil pour le design, aime résoudre des questions difficiles et n'hésite pas à relever des défis. Grâce à sa formation chez SheCodes, elle est parfaitement capable de construire des sites web magnifiques, adaptés aux mobiles et interactifs qui présentent votre entreprise sous un nouveau jour.",
        aboutJoachim:
            "Joachim est le geek du duo. Il a toujours eu un fort intérêt pour la conception de sites web et ne cesse d'acquérir de nouvelles compétences. Grâce à un certificat Full Stack délivré par 4Geeks Academy et à un cours récent sur React Native, il est capable de développer des sites web complexes et modernes, des plateformes d' e-commerce et des applications mobiles.",
        contactHeader: "Contactez-nous",
        contactFirstName: "Prénom",
        contactLastName: "Nom",
        contactPhone: "Téléphone",
        contactEmail: "Email",
        contactCompany: "Entreprise",
        contactInterest: "Je suis intéressé(e) par",
        contactInterestOption1: "Sélectionner",
        contactInterestOption2: "Site One-Page",
        contactInterestOption3: "Site Multi-Page",
        contactInterestOption4: "E-commerce",
        contactInterestOption5: "Autre",
        contactAdditionalInfo: "Infos supplémentaires",
        contactButton: "Envoyer",
        contactIsRequired: "est requis",
        contactNumeric: "Téléphone doit être numérique",
        contactEmailError: "Email invalide",
        contactEmailRequired: "Email requis",
        contactEmailSentSuccess: "Email envoyé !",
        contactEmailSentError: "Échec de l'envoi. Réessayez.",
    },

    dutch: {
        serviceButton: "TERUG NAAR DIENSTEN",
        getInTouch: "Bel ons",
        mailUs: "Mail ons",
        navbarItem1: "HOME",
        navbarItem2: "DIENSTEN",
        navbarItem3: "OVER ONS",
        navbarItem4: "CONTACT",
        navbarLanguage: "TAAL",
        onePage: "ONE-PAGE WEBSITE",
        multiPage: "MULTI-PAGE WEBSITE",
        ecommerce: "E-COMMERCE",
        mobileApps: "APPS",
        introSubHeader1: "Op maat gemaakte websites voor uw bedrijf.",
        introSubHeader2: "Kwaliteit en handgemaakte oplossingen.",
        introSubHeader3: "Uw digitale dromen, gerealiseerd.",
        philosophyHeader: "FILOSOFIE",
        philosophyText1: "Schoon code, design en communicatie.",
        philosophyText2: "Van idee tot lancering leveren wij impact.",
        philosophyClosing: "< Laten we uw online ervaring creëren />",
        whyUsHeader1: "Maatwerk Ontwikkeling",
        whyUsText1:
            "Unieke code voor uw bedrijf. Prachtige, snelle en gebruiksvriendelijke ontwerpen.",
        whyUsHeader2: "Handmatige Code",
        whyUsText2:
            "Handgemaakte sites: snel, veilig, schaalbaar en betrouwbaar.",
        whyUsHeader3: "Toekomstklare Apps",
        whyUsText3:
            "iOS & Android-apps met React Native. Bereik uw publiek overal.",
        whyUsHeader4: "Meertalige Service",
        whyUsText4:
            "We communiceren in Nederlands, Frans en Engels voor duidelijke samenwerking.",
        allServicesHeader: "Hoe we helpen",
        allServicesSubHeader: "Diensten op maat voor uw behoeften",
        allServicesText:
            "We leveren gepersonaliseerde websites en apps om uw bedrijf te onderscheiden.",
        vitrineHeader: "Eenvoudige, impactvolle websites.",
        vitrineIntro1: "Betaalbaar ontwerp: homepagina en contactpagina.",
        vitrineIntro2: "Stel uw bedrijf, diensten en meer voor.",
        vitrineIntro3: "Eenvoudige contactopties: formulieren, links, enz.",
        vitrineIntro4: "Oneindige mogelijkheden.",
        vitrinePerfect: "Ideaal voor",
        vitrineBenefitsHeader: "Voordelen",
        vitrineBox1: "Een enkele pagina met alle belangrijke informatie.",
        vitrinePerfectFor: [
            "Evenementpromotie",
            "Een product/dienst uitlichten",
            "Eenvoudige portfolio's",
            "Starten online",
        ],
        vitrineBenefits: [
            "Bedrijfsdomeinnaam",
            "Snelle en goedkope implementatie",
            "Perfect voor kleine bedrijven",
            "Mobielvriendelijk ontwerp",
        ],
        websiteHeader: "Websites die met u meegroeien.",
        websiteIntro1:
            "Ideaal voor gedetailleerde en georganiseerde bedrijfsinformatie.",
        websiteIntro2: "Van diensten tot resources, toon uw werk.",
        websiteIntro3: "Eenvoudig te navigeren en te verkennen.",
        websitePerfect: "Ideaal voor",
        websiteBenefitsHeader: "Voordelen",
        websiteBox1:
            "Georganiseerde, multi-page ontwerpen voor gemakkelijke navigatie.",
        websitePerfectFor: [
            "Dienstverlenende bedrijven",
            "Resource-sharing organisaties",
            "Portfolio-gedreven bedrijven",
            "Contentplatformen",
        ],
        websiteBenefits: [
            "Snelle toegang tot informatie",
            "Professionele uitstraling",
            "Veelzijdige inhoud",
            "Schaalbaar ontwerp",
        ],
        ecommerceHeader: "Verhoog uw verkoop met online shoppen.",
        ecommerceIntro1: "Eenvoudige en effectieve e-commerce sites.",
        ecommerceIntro2: "Van lokale winkels tot wereldwijde merken.",
        ecommerceIntro3: "Veilige en gebruiksvriendelijke winkels.",
        ecommerceIntro4: "Oneindige mogelijkheden.",
        ecommercePerfect: "Ideaal voor",
        ecommerceBenefitsHeader: "Voordelen",
        ecommerceBox1:
            "Aangepaste of Shopify-webshops, geoptimaliseerd voor verkoop.",
        ecommercePerfectFor: [
            "Eerste online verkoop",
            "Detailhandel met bredere doelgroep",
            "Aangepaste e-commerceoplossingen",
            "Veilige betaalmethoden",
        ],
        ecommerceBenefits: [
            "Lokale en wereldwijde verkoop",
            "24/7 inkomsten",
            "Veilige betalingen",
            "Aantrekkelijke, merkgerichte ontwerpen",
        ],
        appDevHeader: "Mobiele aanwezigheid voor uw merk.",
        appDevIntro1: "Apps die een verschil maken.",
        appDevIntro2: "Voor bestellingen of unieke oplossingen.",
        appDevIntro3: "Snel, betrouwbaar en gebruiksvriendelijk.",
        appDevIntro4: "Ondersteun uw groei op iOS en Android.",
        appDevPerfect: "Ideaal voor",
        appDevBenefitsHeader: "Voordelen",
        appDevBox1: "Aangepaste React Native-apps: efficiënt en schaalbaar.",
        appDevPerfectFor: [
            "Klantencontact",
            "Procesoptimalisatie",
            "Unieke app-ideeën",
            "Schaalbare startups",
        ],
        appDevBenefits: [
            "Altijd verbonden",
            "Automatisering van kerntaken",
            "Eén app voor alle apparaten",
            "Gebruiksvriendelijke ervaring",
        ],
        aboutUsHeader: "The team:",
        aboutLisa:
            "Lisa is the driving force behind Bel'Azur Coding. Without her, this site probably wouldn’t exist. Lisa has an eye for design, loves solving tough challenges, and doesn’t shy away from tackling difficulties. Thanks to her training at SheCodes, she is perfectly capable of building beautiful, mobile-friendly, and interactive websites that showcase your business in a new light.",
        aboutJoachim:
            "Joachim is the geek of the duo. He has always had a strong interest in web design and continuously acquires new skills. With a Full Stack certificate from 4Geeks Academy and a recent course on React Native, he is capable of developing complex and modern websites, e-commerce platforms, and mobile applications.",
        contactHeader: "Neem contact op",
        contactFirstName: "Voornaam",
        contactLastName: "Achternaam",
        contactPhone: "Telefoon",
        contactEmail: "E-mail",
        contactCompany: "Bedrijf",
        contactInterest: "Ik ben geïnteresseerd in",
        contactInterestOption1: "Selecteer",
        contactInterestOption2: "One-Page Website",
        contactInterestOption3: "Multi-Page Website",
        contactInterestOption4: "E-commerce",
        contactInterestOption5: "Anders",
        contactAdditionalInfo: "Extra informatie",
        contactButton: "Verstuur",
        contactIsRequired: "is verplicht",
        contactNumeric: "Telefoonnummer moet numeriek zijn",
        contactEmailError: "Ongeldig e-mailadres",
        contactEmailRequired: "E-mail is verplicht",
        contactEmailSentSuccess: "E-mail verzonden!",
        contactEmailSentError: "E-mail verzenden mislukt. Probeer opnieuw.",
    },
};

export const MyProvider = ({ children }) => {
    const [page, setPage] = useState("allServices");
    const [language, setLanguage] = useState(() => {
        if (typeof window !== "undefined") {
            return localStorage.getItem("userLanguage") || "french";
        }
        return "french"; // Default value if window is not available
    });

    useEffect(() => {
        localStorage.setItem("userLanguage", language);
    }, [language]);

    /* Add all variables to appContext to sync them in the entire application */
    let appContext = {
        page,
        setPage,
        language,
        setLanguage,
        _LANGUAGE_,
    };

    return (
        <MyContext.Provider value={appContext}>{children}</MyContext.Provider>
    );
};

export default MyContext;
